Repository Ashinch/ReadYou, pull requests merged in 2024-07, with the labels that each got.

#761 Add buttons to collapse and expand every group.
  app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedsPage.kt
  app/src/main/java/me/ash/reader/ui/page/home/feeds/FeedsViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, RFC

#795 feat(ui): add referer header with domain extraction for image proxying
  app/src/main/java/me/ash/reader/ui/component/base/RYAsyncImage.kt
Labels: enhancement

#799 fix(rss): get enclosure from SyndEntry attributes first
  app/src/main/java/me/ash/reader/infrastructure/rss/RssHelper.kt
  app/src/test/java/me/ash/reader/infrastructure/rss/RssHelperTest.kt
Labels: bug
